name = "mihir"
compatibility_date = "2026-07-26"

# Serve the static build output instead of running a Worker script
[assets]
directory = "./dist" # Change to "./build" if using Create React App instead of Vite
not_found_handling = "single-page-application"
