name = "mihir"
compatibility_date = "2026-07-26"

# Serve the static build output instead of running a Worker script
[assets]
directory = "./build" # Using Create React App build output
not_found_handling = "single-page-application"
