name = "vintage-resume"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[env.production]
routes = [
  { pattern = "example.com", zone_name = "example.com" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.{js,jsx,ts,tsx,css}"]

[build.upload]
format = "modules"
